#!/bin/bash
echo `pwd`
convert -resize 16x16 ../vaspicon.jpg icon_16x16.png
convert -resize 32x32 ../vaspicon.jpg icon_16x16@2x.png
convert -resize 32x32 ../vaspicon.jpg icon_32x32.png
convert -resize 64x64 ../vaspicon.jpg icon_32x32@2x.png
convert -resize 128x128 ../vaspicon.jpg icon_128x128.png
convert -resize 256x256 ../vaspicon.jpg icon_128x128@2x.png
convert -resize 256x256 ../vaspicon.jpg icon_256x256.png
convert -resize 512x512 ../vaspicon.jpg icon_256x256@2x.png
convert -resize 512x512 ../vaspicon.jpg icon_512x512.png
convert -resize 1024x1024 ../vaspicon.jpg icon_512x512@2x.png
cd ..
iconutil -c icns vasp.iconset
